version: '3.4'
services:
  mysql-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "quantumsoft"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    image: spquantum/backend:q1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/quantumsoft
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      mysql-service:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    image: spquantum/frontend:q1
    ports:
      - "5502:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data:
